version: '2'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: vesseltraefik/app
    environment:
      CONTAINER_ENV: "${APP_ENV}"
      XDEBUG_HOST: "${XDEBUG_HOST}"
      WWWUSER: "${WWWUSER}"
    volumes:
     - .:/var/www/html
    networks:
      vesseltraefik:
      proxy:
        aliases:
          - "${APP_DOMAIN}"
    labels:
      - "traefik.backend=app"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:${APP_DOMAIN}"
      - "traefik.docker.network=proxy"
  redis:
    image: redis:alpine
    volumes:
     - vesselredis:/data
    networks:
      vesseltraefik:
      proxy:
        aliases:
          - "redis${APP_DOMAIN}"
networks:
  vesseltraefik:
    driver: "bridge"
  proxy:
    external: true
volumes:
  vesselmysql:
    driver: "local"
  vesselredis:
    driver: "local"
